import * as Types from '../types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type SubmitMessageMutationVariables = Types.Exact<{
  anonomousUserId: Types.Scalars['String']['input'];
  sessionId: Types.Scalars['String']['input'];
  message: Types.Scalars['String']['input'];
}>;


export type SubmitMessageMutation = { __typename?: 'Mutation', submitMessage: { __typename?: 'ChatSession', id: string, createdAtISO: string, createdById: string, isUserAnonymous: boolean, updatedAtISO: string, programId: string, messages: Array<{ __typename?: 'ChatMessage', value: string, createdAtISO: string, id: string, status: Types.ChatMessageStatus, type: Types.ChatMessageType }> } };


export const SubmitMessageDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"SubmitMessage"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"anonomousUserId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"sessionId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"message"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"submitMessage"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"anonomousUserId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"anonomousUserId"}}},{"kind":"Argument","name":{"kind":"Name","value":"sessionId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"sessionId"}}},{"kind":"Argument","name":{"kind":"Name","value":"message"},"value":{"kind":"Variable","name":{"kind":"Name","value":"message"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"createdAtISO"}},{"kind":"Field","name":{"kind":"Name","value":"createdById"}},{"kind":"Field","name":{"kind":"Name","value":"isUserAnonymous"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAtISO"}},{"kind":"Field","name":{"kind":"Name","value":"messages"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"value"}},{"kind":"Field","name":{"kind":"Name","value":"createdAtISO"}},{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"type"}}]}},{"kind":"Field","name":{"kind":"Name","value":"programId"}}]}}]}}]} as unknown as DocumentNode<SubmitMessageMutation, SubmitMessageMutationVariables>;